<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/05/13 22:43:52

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
