<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/06/15 02:44:54

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
