<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/06/15 02:44:59
sfConfig::add(array(
  'mod_consultafichas_enabled' => true,
  'mod_consultafichas_view_class' => 'sfPHP',
));
