<?php
// auto-generated by sfDefineEnvironmentConfigHandler
<<<<<<< HEAD
// date: 2017/05/27 21:28:19
=======
// date: 2017/05/27 21:36:15
>>>>>>> 9c588d58be3f1a674cbd71568dc3a6e7df34c0b6
sfConfig::add(array(
  'mod_abmfichas_enabled' => true,
  'mod_abmfichas_view_class' => 'sfPHP',
));
