<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/11/20 23:40:07
sfConfig::add(array(
  'mod_seguimientoproyecto_enabled' => true,
  'mod_seguimientoproyecto_view_class' => 'sfPHP',
));
