<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/06/20 20:41:33
sfConfig::add(array(
  'mod_consultafichas_enabled' => true,
  'mod_consultafichas_view_class' => 'sfPHP',
));
