<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/07/15 19:28:30
sfConfig::add(array(
  'mod_cronoactividades_enabled' => true,
  'mod_cronoactividades_view_class' => 'sfPHP',
));
