<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/09/26 02:10:10
sfConfig::add(array(
  'mod_cronoactividades_enabled' => true,
  'mod_cronoactividades_view_class' => 'sfPHP',
));
