<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/10/26 00:14:45
sfConfig::add(array(
  'mod_seguimientoproyecto_enabled' => true,
  'mod_seguimientoproyecto_view_class' => 'sfPHP',
));
