<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/06/11 21:00:05
sfConfig::add(array(
  'mod_cronoactividades_enabled' => true,
  'mod_cronoactividades_view_class' => 'sfPHP',
));
