<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/07/01 20:08:36
sfConfig::add(array(
  'mod_consultafichas_enabled' => true,
  'mod_consultafichas_view_class' => 'sfPHP',
));
